### ISSUE TITLE
UTF-8 Issue

### ISSUE THREAD

**Issue by vdanelia** [semplon/GeniXCMS#10]
Hello friends I'm testing the cms
I found that It doesn't support unicode utf-8 until I manuali added it in index
"<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />"
it would be a good if you add this option from admin panel

After I added it works, now I can write in Georgian Language without any problem

**Comment by semplon** [comment]
Thanks for your report. I'll add it on the next update.

**Comment by semplon** [comment]
this issue was fixed.
