### ISSUE TITLE
Cannot access admin on localhost

### ISSUE THREAD

**Issue by orionseye** [semplon/GeniXCMS#102]
Hi,

just try to install GeniXCMS on   localhost/GeniXCMS  but after entering admin credentials, i get 404 not found error.
What's the procedure installing on a sub-folder? Does GeniXCMS need rewrite rules enabled with htaccess?
Actually, the URL i stuck in is http://localhost/GeniXCMS/?step=4

**Comment by semplon** [comment]
Hi @orionseye what happen when You open this page ? http://localhost/GeniXCMS/

GeniXCMS doesn't require rewrite rules. but it's best with rewrite rule enabled.

**Comment by semplon** [comment]
okay, cool. yes i see that. will be fixed on the next update.
