### ISSUE TITLE
Module Menu options Is Not Displayed When adding new menu

### ISSUE THREAD

**Issue by vdanelia** [semplon/GeniXCMS#11]
When I wanted to add module as Menu, in Menu Type in mod dropdown list the mods aren't displayed, Please correct it.

**Comment by semplon** [comment]
The module menu is still in development. Will be added with new features and backend features.

thank You

**Comment by vdanelia** [comment]
Thanks :+1:

**Comment by semplon** [comment]
not yet. i'm still find a simple solutions for that.

**Comment by semplon** [comment]
done https://github.com/semplon/GeniXCMS/commit/d885eb20006099262c0278932b9f8aca3c1ac97f
