### ISSUE TITLE
Question About Multilingual Content

### ISSUE THREAD

**Issue by vdanelia** [semplon/GeniXCMS#13]
Semplon I'm testing your CMS it's really very good and smart... I found the cms language file, so as I guessed the cms supports multilingual content, but couldn't figure out how to switch between languages,  or how to enter post in 2 Languages (Can't found Language data selector, container) I have translated the English file to Georgian (My native language).

Thank you in Advanced

**Comment by semplon** [comment]
This is a complex things to do. I think i'll create another branch and work for it.

**Comment by semplon** [comment]
I'm starting working with multilanguage. see this branch https://github.com/semplon/GeniXCMS/tree/multilang

**Comment by semplon** [comment]
this issue is closed. I've already commit multilanguage at the master branch and on progress for more improvement.
