### ISSUE TITLE
CMS System Language Enhancement

### ISSUE THREAD

**Issue by vdanelia** [semplon/GeniXCMS#15]
CMS System Language Can be changed manually from config.php, but it would be more convenient to change it from Admin Panel (From The Settings Page: Select Language or something like)

**Comment by semplon** [comment]
It would be great. So people won't edit the config file manually and messed up the code.
I'll add it at the next release update. 
Thanks for the suggestions.

**Comment by semplon** [comment]
this issue was fixed and i will close it for now.
