### ISSUE TITLE
Mysql storing wrong character format

### ISSUE THREAD

**Issue by Scavolini-Pesaro** [semplon/GeniXCMS#16]
Congratulations for the CMS, it will be very good.

I found a big mistake: If you save a post in admin with utf8 characters (after you add the missing utf8 charset line to admin header.php), the special utf8 characters saved in wrong format at the mysql database, like & aacute;  (the good format is á ) I dont know which file causing the wrong format (I thought typo.class.php or db.class.php, but I don't find the problem). I hope you can solve this problem, and your great cms will save in good format at the mysql database. (If you view the website there is no problem, but the database storing wrong format, and this is not good).

**Comment by semplon** [comment]
Thanks @Scavolini-Pesaro  for reporting the issue. about that it was generated by Typo::cleanX(). All inputted values are converted by htmlentities for security reason to prevent SQL Injection. To reverse it use Typo::Xclean() function.

I hope that can explain the problem why i do that. 

thanks

**Comment by semplon** [comment]
this issue was fixed and i will close it for now.

**Comment by vdanelia** [comment]
Ok Thanks Semplon
