### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by tucuta** [semplon/GeniXCMS#17]
I like this cms.
I have this error in my installation:
```
Fatal error: Call to undefined function openssl_random_pseudo_bytes() in C:www\GeniXCMS\inc\lib\Typo.class.php on line 117
```
Any solution ... ???

Thanks in advance for the help you can give me.

**Comment by semplon** [comment]
Hello, Thank You for installing GeniXCMS. Please make sure your PHP version is above 5.3. And then, please make sure the php openssl library was installed. 

Locate the php.ini file. change ;extension=php_openssl.dll to extension=php_openssl.dll
