### ISSUE TITLE
CDN Problem, Need Some Implementation

### ISSUE THREAD

**Issue by vdanelia** [semplon/GeniXCMS#26]
Today when working with the script for hard testing purposes the CDN site cdnjs.cloudflare.com was stuck and i was not able to work correctly, had some troubles... after the cloudflare went ok the script itself went ok too...
So We need some improvements: (If the CDN fails the script must work from local js files and resources)
This is very important!

**Comment by semplon** [comment]
I fix this by load local assets for admin pages. i hope this helpfull
