### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by Scavolini-Pesaro** [semplon/GeniXCMS#27]
Hello Semplon!

I have a question for you, I still testing your promising CMS. There is an easy solution for user change their language settings? Because I see that at admin the language selection working good, but I think it will be very good if visitors (guests) could change language settings via the website index template, like index.php?lang=it (Italian) or index.php?lang=fr (French) etc.. And another question: The use of language variable at templates is the same in admin templates? Like <?=variable;?>   Thank you for the answers!

**Comment by semplon** [comment]
Thank You @Scavolini-Pesaro for testing GeniXCMS. Yes You are right. In the future visitors can change the language, this features will be implemented along with the multi language feature, including posts, categories, menus, etc. This features still in development right now. 

Yes, It's the same.

**Comment by semplon** [comment]
Hello, I'm starting working with multilanguage. seet this branch
https://github.com/semplon/GeniXCMS/tree/multilang

thanks
