### ISSUE TITLE
Error During Logout

### ISSUE THREAD

**Issue by GaneshKandu** [semplon/GeniXCMS#54]
Hi Its Ganesh Kandu
I have Installed GeniXCMS 0.0.7 in My PC and getting an error on logout
<br />
<b>Warning</b>:  session_destroy(): Trying to destroy uninitialized session in <b> /geni289/inc/lib/Session.class.php</b> on line <b>103</b>
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at  /public_html/geni289/inc/lib/Session.class.php:103) in <b> /public_html/geni289/gxadmin/logout.php</b> on line <b>27</b><br />

**Comment by semplon** [comment]
Hi @GaneshKandu, Thanks for submitting the issue. I'll fix it soon.

**Comment by GaneshKandu** [comment]
Please Reply When you done :+1:  Thanks

**Comment by semplon** [comment]
this issue was fixed. please try to download our latest master version.

thanks

**Comment by GaneshKandu** [comment]
Hi, am Getting Blank Page on 
http://{{ ip }}/genix/gxadmin/ &
http://{{ ip }}/genix/

**Comment by semplon** [comment]
hello, can you send me the error log ? 
if you success installing it. please go to inc/config and open config.php
set this value `error_reporting(0);` to `error_reporting(E_ALL);`
and then send me the error reported by the browser. 

thanks

**Comment by GaneshKandu** [comment]
got That 


Parse error: syntax error, unexpected '[' in /home/soft/public_html/manual/genix/inc/lib/Router.class.php on line 99

**Comment by semplon** [comment]
thanks, please open `inc/lib/Router.class.php`
go to line `84`. replace it with this code

```php
    public static function run () {

        $m = self::match();
        // print_r($m);
        if (is_array($m)) {
            # code...

            $val = self::extract($m[0], $m[1]);

            if (isset($val) && $val != null ) {

                return $val;

            }else{
                $val = ['error'];
                return $val;

            }

        }else{

            $val = ['error'];
            return $val;

        }
    }
```

let me know if it's work

thanks

**Comment by GaneshKandu** [comment]
still Getting Same 

<br />
<b>Warning</b>:  require({{httpdoc}}/manual/genix/gxadminautoload.php): failed to open stream: No such file or directory in <b>{{httpdoc}}/manual/genix/gxadmin/logout.php</b> on line <b>24</b><br />
<br />
<b>Warning</b>:  require({{httpdoc}}/manual/genix/gxadminautoload.php): failed to open stream: No such file or directory in <b>{{httpdoc}}/manual/genix/gxadmin/logout.php</b> on line <b>24</b><br />
<br />
<b>Fatal error</b>:  require(): Failed opening required '{{httpdoc}}/manual/genix/gxadminautoload.php' (include_path='.:/usr/local/apps/php54/lib/php') in <b>{{httpdoc}}/manual/genix/gxadmin/logout.php</b> on line <b>24</b><br />

**Comment by semplon** [comment]
ah, thank you for bringing this up. i miss something.

at the `/gxadmin/logout.php` match with this code

```php
define('GX_PATH', realpath(__DIR__ . '/../'));
define('GX_LIB', GX_PATH.'/inc/lib/');
define('GX_MOD', GX_PATH.'/inc/mod/');
define('GX_THEME', GX_PATH.'/inc/themes/');
define('GX_ASSET', GX_PATH.'/assets/');

require(GX_PATH."/autoload.php");

try {
    new System();
} catch (Exception $e) {
    echo $e->getMessage();
}

Hooks::run('user_logout_action');
Session::destroy();
header("Location: index.php");
```

at the `/logout.php`  match the content with this code

```php
define('GX_PATH', realpath(__DIR__ . '/'));
define('GX_LIB', GX_PATH.'/inc/lib/');
define('GX_MOD', GX_PATH.'/inc/mod/');
define('GX_THEME', GX_PATH.'/inc/themes/');
define('GX_ASSET', GX_PATH.'/assets/');

require(GX_PATH."/autoload.php");

try {
    new System();
} catch (Exception $e) {
    echo $e->getMessage();
}

Hooks::run('user_logout_action');
Session::destroy();
header("Location: index.php");
```

let me know if it's work. 

thanks

**Comment by GaneshKandu** [comment]
Working very well :+1:

**Comment by semplon** [comment]
cool, thank you for reporting the issue

**Comment by GaneshKandu** [comment]
Thanks to Fix
