### ISSUE TITLE
Smart URLs in a Sub-Directory not worked

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#56]
Hello Developers,

I have a problem with the smart URLs in the sub-directories. My Genix-blog is under http://wpzweinull.ch/cms/genix and is not as accessible. But I have already written a test article and this is attainable.

How can it be that I can not explain it ?!

In the .htaccess file now looks like this:

    RewriteEngine On
    RewriteBase /cms/genix/

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.+)$ index.php [QSA,L]

And in the config.php file in the Smart URLs it looks like:

    define('SMART_URL', 'true'); //set 'true' if you want use SMART URL (SEO Friendly URL)
    define('GX_URL_PREFIX', '.html');

Whether you help me maybe so can ??

On my server is installed PHP 5.5 and the latest version of mySQL. But because it should not be, I think times.

**Comment by semplon** [comment]
Hello @AlexL777, thank you for submitting the issue. I will check and test it.

**Comment by semplon** [comment]
Hello, This problem had been fixed.

**Comment by AlexL777** [comment]
Thank you, the problem is now eliminated with me. I still have an issue with the Disqus comments.

**Comment by semplon** [comment]
what issue did you had with Disqus comment ?
