### ISSUE TITLE
How do you implement Disqus comments at Genix CMS

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#57]
Hello Developers,

I would like to put in this CMS on Disqus comments and only needs to remove Facebook Comments. How can I realize it?

Disqus code could integrate the template and probably I let even the Facebook comments.

Which file in the template is responsible?

Thanks in advance.

**Comment by semplon** [comment]
Hello @AlexL777 

To change the Facebook comment with Disqus is easy. Just open the `single.php` file inside the theme folder. If you familiar with wordpress i think You will change it fast. 
See image below for details.
![open single-php](https://cloud.githubusercontent.com/assets/3163608/13749574/b32b494a-ea34-11e5-9fa7-7e53abc3348a.png)

after You open the single.php file, scroll down until you see Comments part. See image for illustration.
![replace with disqus](https://cloud.githubusercontent.com/assets/3163608/13749628/e1d6dc8c-ea34-11e5-8287-9647a167b89d.png)

Just replace the selected area with the Disqus comments script. Don't forget to include the required Disqus javascript if there are any.

I hope this could help.

Thanks

**Comment by AlexL777** [comment]
Thanks for your tip with the comments, but unfortunately I get so see a white page and apparently it does not work that way.

The code in the single.php is with me then so:

    
    <h3>Comments</h3>
                                <div id="disqus_thread"></div>
    <script>
    /**
     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
     */
    /*
    var disqus_config = function () {
        this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
        this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };
    */
    (function() {  // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');

        s.src = '//genixdeblog.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

                                </div>
                            </div>

                                ";


Whether you need it might do differently ??

**Comment by semplon** [comment]
Hello, Sorry I forgot to tell you that it's inside echo. the `"` sign inside the echo should be backslashed first before. I just modified it and test it at my localsite. use this code.

```
<div id=\"disqus_thread\"></div>
<script>
/**
 *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
 *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
 */
/*
var disqus_config = function () {
    this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() {  // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');

    s.src = '//genixdeblog.disqus.com/embed.js';

    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href=\"https://disqus.com/?ref_noscript\" rel=\"nofollow\">comments powered by Disqus.</a></noscript>
```

## See it in action.

![disqus](https://cloud.githubusercontent.com/assets/3163608/13768012/c4860ed6-eaa3-11e5-8391-08cbe804ee31.png)

**Comment by AlexL777** [comment]
Thank you, just awesome and it works. So now I have perhaps a little better chance of feedback in the blog than Facebook comments :)

Thanks again!

**Comment by semplon** [comment]
You're welcome :D
