### ISSUE TITLE
a security issue [sql injection]

### ISSUE THREAD

**Issue by Strikersb** [semplon/GeniXCMS#58]
Hi,friend

Im Striker, from China

a vulnerability discovered in GeniXCMS 0.0.8

Please respond to [song@secbox.cn](mailto:song@secbox.cn) for more details.

Thanks

**Comment by semplon** [comment]
hello, i've already sent the email to your email. 

thanks for bringing up the issue.

**Comment by Strikersb** [comment]
Could you please help me to apply for a CVE-ID?
I really want CVE-ID  @semplon

**Comment by semplon** [comment]
Hi, thanks for the details. I will update it soon. for getting your own CVE-ID you can get it from mitre.org website. Below are some links how to get CVE-ID

http://cve.mitre.org/cve/request_id.html 

It's you who sould ask the ID by sending email to them.

I hope this could help You.

Once again, thanks for the issue.

**Comment by semplon** [comment]
fixed https://github.com/semplon/GeniXCMS/commit/d885eb20006099262c0278932b9f8aca3c1ac97f
