### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by l3m0n** [semplon/GeniXCMS#59]
/inc/lib/Control.class.php
`    public static function frontend()
    {
        $arr = ['ajax', 'post', 'page', 'cat', 'mod', 'sitemap', 'rss',
                    'account', 'search', 'author', 'tag', 'thumb', 'default'];
`   

array error,i cann't install,

why not?
`
 public static function frontend()
    {
        $arr = array('ajax', 'post', 'page', 'cat', 'mod', 'sitemap', 'rss',
                    'account', 'search', 'author', 'tag', 'thumb', 'default');
`

**Comment by semplon** [comment]
hello @l3m0n thanks for reporting the issue. had you succeed after changed that to array ? 
it's working fine at my server. which PHP version did you use ?

**Comment by l3m0n** [comment]
php 5.3.29

**Comment by semplon** [comment]
@l3m0n thank you, i will fix that problem, since there are still people using that version.

**Comment by l3m0n** [comment]
You're welcome.I also found a security problem,

```
if (isset($_GET['activation'])) {
	$activation = Typo::strip(Typo::cleanX($_GET['activation']));
	$usr = Db::result(sprintf("SELECT * FROM `user` WHERE `activation` = '%s' LIMIT 1", $activation));
```

the version is 1.0，diff version 0.8

```
if (isset($_GET['activation'])) {
    # code...
    $usr = Db::result(sprintf("SELECT * FROM `user` WHERE `activation` = '%s' LIMIT 1", $_GET['activation'] ));
```

I don't think it's safe

`$activation = Typo::strip(Typo::cleanX($_GET['activation']));`

you can see:

`http://demo.genixcms.org/register.php?activation=1%27and%20updatexml(1,(select%20version()),1)%23`

Typo class can defend some XSS,but sqli cann't
login.php and forgotpassword.php also have some problem.

i think you can use this function `addslashes`,of course, you also need to judge GPC so that determine whether you can use this function

**Comment by semplon** [comment]
@l3m0n thank you for the report, i'll fixt that soon.

**Comment by semplon** [comment]
after i check the demo site codes, it looks like that's still old version 1.0 codes. it's the early development of version 1.0 which hadn't secured yet. 
the `$activation = Typo::strip(Typo::cleanX($_GET['activation']));` code secure very well at my localhost which had the latest development.

**Comment by l3m0n** [comment]
ok, then I'll keep looking.
which php version did you use?

**Comment by semplon** [comment]
i'm using 5.6.27
