### ISSUE TITLE
Possible XSS Vulnerabilities in User Prompt Function

### ISSUE THREAD

**Issue by Xyntax** [semplon/GeniXCMS#63]
Data in `$data['alertSuccess']` and `$data['alertDanger']` is passed directly to the DOM without any filtering, resulting in XSS vulnerability.

```
<?php
if (isset($data['alertSuccess'])) {
    echo '<div class="alert alert-success" >
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">'.CLOSE.'</span>
        </button>
        ';
    foreach ($data['alertSuccess'] as $alert) {
        echo "$alert\n";
    }
    echo '</div>';
} elseif (isset($data['alertDanger'])) {
    //print_r($data['alertDanger']);
    echo '<div class="alert alert-danger" >
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">'.CLOSE.'</span>
        </button>
        <ul>';
    foreach ($data['alertDanger'] as $alert) {
        echo "<li>$alert</li>\n";
    }
    echo '</ul></div>';
} ?>
```

![pic](http://static.cdxy.me/Screenshot%20from%202017-01-13%2016-14-33.png)

Related codes

* https://github.com/semplon/GeniXCMS/blob/master/register.php#L166
* https://github.com/semplon/GeniXCMS/blob/master/login.php#L117
* https://github.com/semplon/GeniXCMS/blob/master/inc/lib/System.class.php#L285
* https://github.com/semplon/GeniXCMS/blob/master/inc/mod/newsletter/options.php#L77

Untrusted input data is in different ways, filter the output node may be a good idea.

Whats your opinion?

**Comment by semplon** [comment]
yes you are right, i hadn't filter the strings. i'll fix this soon. thanks @Xyntax
