### ISSUE TITLE
XSS in inc/lib/Site.class.php when view post

### ISSUE THREAD

**Issue by gaohuailiang** [semplon/GeniXCMS#76]
Hello, I found a XSS vulnerability in URL: http://128.18.22.17/GeniXCMS/?post=1. Please confirm.

![xss](https://cloud.githubusercontent.com/assets/28896605/26354671/3150fd64-3ff8-11e7-9be5-069beb67e875.png)

1.Use the latest version of GeniXCMS in github(20170523).
2.Use Internet Explorer.

------------------------------------
Author: gaohuailiang
E-mail: gaohuailiang@huawei.com
Huawei Weiran Labs
------------------------------------

**Comment by semplon** [comment]
please tell me what version did you use ?
see at the bottom of the dashboard page.

**Comment by gaohuailiang** [comment]
Copyright 2017 GeniXCMS 1.0.2

I cloned the latest code in github yesterday : https://github.com/semplon/GeniXCMS

The vulnerable code is in inc/lib/Site.class.php:
line 92: <link rel=\"canonical\" href=\"".$canonical."\" />

The root cause is $canonical param not checked correctly in blow function, so that attackers could wirte some script code in uri, like http://your-ip/GeniXCMS/?post=1"><script>alert(/XSS/);</script>

170     public static function canonical()
171     {
172         $protocol = stripos($_SERVER['SERVER_PROTOCOL'],'https') === true ? 'https://' : 'http://';
173 
174         return $protocol.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
175     }
