### ISSUE TITLE
GeniXCMS is now stable and safe?

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#77]
Hello Developers,

On the basis of the many security issues here, you also get a first impression of the GeniXCMS. Is it now more stable and safer, or do I have to worry as a Genix user?

I installed it today in version 1.0.2 and would like to collect my experiences with this OpenSource CMS.

Installation was the problem that I forgot to specify the slash `/` during the installation. So, JS/CSS were not loaded and I was wondering why the hell it does not work.

Today I got to it and installed everything correctly 👍 

Thank you for this CMS, but unfortunately only in English or is there German Language somewhere?

**Comment by semplon** [comment]
Hello @AlexL777 thank you for testing GeniXCMS. We had some updates with our latest stable 1.1.0 but not released yet. You can try this version at the demo site https://demo.genix.id

This 1.1.0 version is more stable and with all mandatory securities issues. We add more features and improvement. I hope this will help you creating a great website. With included magazine style Theme - GneeX. 

Unfortunately, we had no language other than English and Indonesian. We had no translation team yet to translate it into another language. 

If you had time, you can translate it if you want. And push it here. 

Once again, Thank You for testing GeniXCMS. 

We will release the version 1.1.0 soon.

**Comment by AlexL777** [comment]
Hi,
Thank you for the short and comprehensible insight into the GeniXCMS. So a blogpost you can already look at my Genix website at https://genixcms.wpzweinull.ch/suchmaschinen-freundliche-urls-beim-genixcms-die-smart-urls-genannt.html :smile:

I have installed the last branch of GitHub on the blog. GenixCMS runs with me on Ubuntu 16, managed server, PHP 7.0 and subdomain as well as with MySQL 5.6. Good work, then, you have done, and there I will surely pursue the development.

**Comment by semplon** [comment]
Hello @AlexL777 i just release version 1.1.0 with a lot of features. please check

thanks

**Comment by AlexL777** [comment]
Hi,

Thank you very much, have just made an upgrade successful and now look a bit in the backend. If I should find bugs, I would like to report it here in the issues.

Otherwise, thanks for the new version and I can now continue to work 😄
