### ISSUE TITLE
two loagic bugs in latest product

### ISSUE THREAD

**Issue by cL0und** [semplon/GeniXCMS#78]
Hello Developers,i has found two logic bugs in your product，which maybe cause some problems

I hope this helps you.
the first point:
**at register.php line53**
`if (!User::isSame($_POST['pass1'], $_POST['pass1'])) `
Here, you use the same password for testing

the Second point:
**at register.php line53**
`User::isExist($_POST['userid'])) `,
Let's follow up this function
**User.class.php line222**
`   public static function isExist($user, $except='')
    {
        if ($except != '') {
            $id = Typo::cleanX(Typo::strip($except));
......
`
Let's follow up Typo::strip
**Type.class.php line101**
`public static function strip($text, $tags = '', $invert = false)
    {
        preg_match_all('/<(.+?)[\s]*\/?[\s]*>/si', trim($tags), $tags);
        $tags = array_unique($tags[1]);

        if (is_array($tags) and count($tags) > 0) {
            if ($invert == false) {
                /*return preg_replace('@<(?!(?:'. implode('|', $tags) .')\b)(\w+)\b.*?>.*?</\1>@si', '', $text); */
                $text = preg_replace('@<(?!(?:'.implode('|', $tags).')\b)(\w+)\b.*?>@si', '', $text);
                $text = preg_replace('@</(?!(?:'.implode('|', $tags).')\b)(\w+)\b.*?>@si', '', $text);
            .......`
We can see that the regular expressions here are removed from the corner brackets.
For example:if username is `admin<script>` then the function will return `admin`.
But  finally, the data does not check the same name before entering the database.
so it will cause a large problem we can block any member's account if we know his username.
why? because in login.php line 6 $c != 1 because there are two There are two users called `admin`

 That's what I want to say. If I don't make it clear, please contact me 

rigist the same user who named "root"
![pic](https://user-images.githubusercontent.com/30562775/29026808-44ae3072-7bb0-11e7-9d7a-01e396820d15.PNG)

we can see there are two same users except group
![pic2](https://user-images.githubusercontent.com/30562775/29026810-44c546ea-7bb0-11e7-8001-01cd55e47e97.PNG)

admin "root" can not log in!!!
![pic3](https://user-images.githubusercontent.com/30562775/29026809-44b9a916-7bb0-11e7-8907-fdd38f5fd027.PNG)

**Comment by semplon** [comment]
thank you for bringing this issue. i will do the fix on the next update. 

sorry for long reply, my laptop was stolen and all of my data was lost. 

once again, thank you.

**Comment by cL0und** [comment]
Hello Developers,i was author of *two loagic bugs in latest product.*
I hope you can give me a CVE,if you agree it will bacome my first CVE in my
life,think you.
my id is cL0und

2017-08-26 8:11 GMT+08:00 Puguh Wijayanto <notifications@github.com>:

**Comment by semplon** [comment]
I've already check the script. the point 1 is not a bug, it just to check whether the inputed password are same or not. 

and the second point i got this as issue. and will be commit the fix

for cve, please request cve id at https://cve.mitre.org/cve/request_id.html

**Comment by cL0und** [comment]
Ok thank you very much

2017-09-05 12:47 GMT+08:00 Puguh Wijayanto <notifications@github.com>:

**Comment by andre-checkmarx** [comment]
> I've already check the script. the point 1 is not a bug, it just to check whether the inputed password are same or not.

Selamat pagi!
I think you have misread the code. The following line uses the same `POST` argument twice:

https://github.com/semplon/GeniXCMS/blob/dd6e07f0c7525b025110efc250bb23b29309a820/register.php#L53

So you're effectively doing `p1 == p1` instead of `p1 == p2`.

**Comment by semplon** [comment]
@andre-checkmarx ah you are right. i will take a look. and fixed it. 
it's been so long not updated since i am trying to migrate to bootstrap 4.

**Comment by andre-checkmarx** [comment]
Awesome, glad I could help!
Also, do you have a way we can contact you privately, to discuss other vulnerabilities?

**Comment by semplon** [comment]
yes you can contact me at telegram @metalgenix
