### ISSUE TITLE
URL-Rewriting not working

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#79]
Hello Developers,

I upgraded to Genix 1.1 today and unfortunately now the URLs in the blog do not work.

A sample URL would be this at https://genixcms.wpzweinull.ch/projektstart-mit-dem-genixcms-auf-genixcms-wpzweinull-ch.html

How can I fix the problem?

Thanks in advance.

P.S. I put on the magazine layout, which was adjustable.

With the blog layout I had it earlier and there everything worked with the URLs.

**Comment by semplon** [comment]
can you change the variable at  config.php from error_reporting(0); to error_reporting(E_ALL); 
and let me see the error

**Comment by AlexL777** [comment]
```
Warning: Unterminated comment starting line 2 in /xxxxxxxxxxxxxxx/genixcms.wpzweinull.ch/inc/config/config.php on line 2

Warning: mysqli::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /xxxxxxxxxxxxxxxxxx/genixcms.wpzweinull.ch/inc/lib/Db.class.php on line 74

Warning: mysqli::__construct(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /xxxxxxxxxxxxxxxxxx/genixcms.wpzweinull.ch/inc/lib/Db.class.php on line 74
Database Error

Something went wrong with the database.
php_network_getaddresses: getaddrinfo failed: Name or service not known
```

**Comment by semplon** [comment]
did the DBHOST at the config using domain ? not localhost ?

**Comment by AlexL777** [comment]
OK, Thanks, I have made and now when calling a blog post this error.

```
Fatal error: Uncaught Error: [] operator not supported for strings in /xxx/genixcms.wpzweinull.ch/inc/lib/Posts.class.php:473 Stack trace: #0 /xxxx/genixcms.wpzweinull.ch/inc/themes/gneex/single.php(35): Posts::tags('4') #1 /xxxx/genixcms.wpzweinull.ch/inc/lib/Theme.class.php(39): include('/www/htdocs/w01...') #2 /xxxxx/genixcms.wpzweinull.ch/inc/lib/Control/Frontend/post.control.php(50): Theme::theme('single', Array) #3 /xxxx/genixcms.wpzweinull.ch/inc/lib/Control.class.php(68): include('/www/htdocs/w01...') #4 /xxxx/genixcms.wpzweinull.ch/inc/lib/Control.class.php(183): Control::incFront(Array, Array) #5 /xxxxx/genixcms.wpzweinull.ch/inc/lib/Control.class.php(112): Control::route(Array) #6 /xxxx/genixcms.wpzweinull.ch/inc/lib/GxMain.class.php(63): Control::frontend() #7 /xxxx/genixcms.wpzweinull.ch/index.php(30): GxMain->index() #8 {main} thrown in /xxxx/genixcms.wpzweinull.ch/inc/lib/Posts.class.php on line 473
```

What can be the cause?

Thanks in advance.

**Comment by semplon** [comment]
it's kind of weird, i just testing it and it's working fine at my server.

**Comment by AlexL777** [comment]
Hi,

this is interesting. I have switched instead of PHP 7.x to PHP 5.6 and see, since everything works again and the posts with the Maganzin layout are again displayed.

With which version of PHP could you test it with you?

Thanks in advance.

**Comment by semplon** [comment]
hmmm i see. i'm using PHP 5.6.   i think i should test it with PHP 7.x

**Comment by AlexL777** [comment]
OK thanks. Yes, it does not seem to work with PHP 7.0-7.1. With PHP 5.6 this goes.
