### ISSUE TITLE
The file for the password reset does not exist in gxadmin

### ISSUE THREAD

**Issue by raisiqueira** [semplon/GeniXCMS#8]
Hi!
The file for the password reset does not exist in gxadmin. By clicking on forgot password, we are redirected to a page that does not exist (forgotpassword.php).

**Comment by semplon** [comment]
Hi, 
Thanks for the report. I'll add that on the next update.

**Comment by semplon** [comment]
https://github.com/semplon/GeniXCMS/commit/7b61a1ca7205be609b39f4e7303317d93f6f8c7d

just commit a forgotpassword.php files on both frontpage and admin area.
and add more improvement.
