### ISSUE TITLE
How can I display recent Comments in the Sidebar

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#81]
Hello Developers,

is there a solution, as I can show recent comments at the Magazine Theme in the right Sidebar?

That would be very helpful, because the Blog Readers see the same, aha, it was commented and that makes the whole thing also exciting.

Thanks in Advance.

**Comment by semplon** [comment]
nice question. i will add this feature later.

**Comment by AlexL777** [comment]
Ok, Thanks!!

**Comment by semplon** [comment]
hello @AlexL777 since You had contribute to GeniXCMS i'll give you Jetbrains Opensource License for you.

please provide your email address so i can send you the license code. thanks

**Comment by AlexL777** [comment]
Hi @semplon !
Many Thanks.

That pleases me very much!!

My mail is power_sash@gmx.net

**Comment by semplon** [comment]
I've already sent the license, you can delete your email detail. thanks
