### ISSUE TITLE
I would like to give some Feedback on v1.1.1

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#82]
Hello Developers,

thank you in the first place for the new version `v1.1.1`. The upgrade I succeeded today and afterwards I looked more closely in the backend.

The options for adjusting the size of the headings I have found and also so everything looks passable. I could write something about this at https://genixcms.wpzweinull.ch/genix-v1-1-1-cms-update-erschienen-bugfixes-und-sicherheit.html. This is then for German Users of Genix CMS.

On the upcoming feature with the last comments in the sidebar I am already looking and that will be very useful.

Otherwise good work and I satisfactory for myself. Thank you!

**Comment by semplon** [comment]
Hello @AlexL777 

Thank You, I just release version 1.1.2 which had recent comments. Please upgrade it to version 1.1.2

Thanks

**Comment by AlexL777** [comment]
Hi,

Thanks for that and I could already upgrade. Everything looks good now with the last comments in the sidebar.

**Comment by semplon** [comment]
awesome.
