### ISSUE TITLE
Feature Requests: Word Counter in Editor and TagCloud for the Sidebar

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#83]
Hi Developers,

I now work very much with the GenixCMS and have thought of two function requests.

Can a word counter be implemented in the editor? This is where written words are counted and so the blogger knows, aha, so and so many words he has already written.

The second function you would want is the TagCloud for the sidebar. If you could still set the number of tags, it would be great. Also, perhaps a tag counter would be possible.

The tags are counted and the number of the tag is displayed next to the tag in the TagCloud.

Would all this be possible?

Thanks in advance and I hope that I have not too many wishes 😸

**Comment by semplon** [comment]
hello @AlexL777 that would be good. I'll manage it with the next release. 

thank you

**Comment by AlexL777** [comment]
Hi,

ok, thank you in advance. Since I am looking forward to these two features.

**Comment by semplon** [comment]
this features already implemented, see demo https://demo.genix.id/
