### ISSUE TITLE
Feedback about Genix 1.1.5

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#86]
Hello Developers,

thanks in the first place for the new Genix 1.1.5 update. It has worked and you have also improved the security. I always welcome this as a CMS blogger. The Footer navigation works and the TagCloud is displayed.

A question on the edge I have nevertheless.

Can I somehow set that the TagCloud only once in the sidebar and not in the footer is narrowed.

So it might be double. Perhaps I have overlooked the tag setting in the admin.

Thanks in Advance.

**Comment by semplon** [comment]
hello @AlexL777 thank you for the suggestion. yeah it's a little bit too much when had two tag cloud in one page. i think i will add some options at the theme options so we can choose to show the tag at the footer or sidebar. 

thanks,

**Comment by AlexL777** [comment]
Hi @semplon ,

Thank you for greeting my suggestion. That would be good if you can still set the TagCloud via an option.

Since I have just a lot of patience when you make a new update, I will also update with me.

**Comment by semplon** [comment]
this issue closed at version v1.1.7
