### ISSUE TITLE
How can I embed Youtube Videos in Genix CMS?

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#87]
Hello Developers,

I would also like to work with Youtube videos in Genix CMS. How can I embed them so that they appear in the blog post? Is there a possibility and maybe we need a new tool for the editor in Genix CMS?

Thanks in Advance.

**Comment by vdanelia** [comment]
it's easy, embed it via tinymce editor

**Comment by AlexL777** [comment]
Thanks for the helpful tip. So I already embedded the videos.
