### ISSUE TITLE
Advisory from Netsparker - GeniXCMS 1.1.5 vulnerability 

### ISSUE THREAD

**Issue by DanielBishtawi** [semplon/GeniXCMS#88]
Hello,

While testing the Netsparker web application security scanner we identified a vulnerability in GeniXCMS 1.1.5. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed? 

Please email me: daniel at netsparker dot com

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by semplon** [comment]
I emailed You, 

Thanks,

**Comment by fgeek** [comment]
@semplon Is this vulnerability fixed or do you need more information, help or something? Netsparker has announced this vulnerability publicly:

https://lists.openwall.net/full-disclosure/2019/01/04/5
https://www.netsparker.com/web-applications-advisories/ns-18-039-cross-site-scripting-in-genixcms/

**Comment by semplon** [comment]
oh yes, i miss this security issue. i will fix it soon. thanks for the info @fgeek
