### ISSUE TITLE
Are Comments possible under Pages - Magazine Layout

### ISSUE THREAD

**Issue by AlexL777** [semplon/GeniXCMS#89]
Hello Developers,

I would also like comments under the pages on the Genix CMS. Would it work technically?

Thanks in Advance.

P.S. I use the magazine layout.

**Comment by semplon** [comment]
sure it can. You can add the code like this

go to inc/themes/gneex/
open page.php
go to line 21 and then press enter
paste this code
```if (Comments::isEnable()) {
                                echo '
                                <div class="col-sm-12">
                                    <h3>Comments</h3>
                                    <div class="row">'.Comments::form().'<div class="clearfix">&nbsp;</div><hr />'.Comments::showList($comment).'</div>
                                </div>
                                    ';
                            }
```

i hope this work

**Comment by AlexL777** [comment]
Hi,
Thanks for that! 

I only have this warning on one page. 

    Warning: Division by zero in /xxxxxxxxxxxxxxx/genixcms.wpzweinull.ch/inc/lib/Paging.class.php on line 85

How can it fix?

Thanks in advance.

**Comment by semplon** [comment]
ah, i see. i forgot to add the `$comment` variables.
replace the code with this.
```
$comment = array(
     'offset' => 0,
     'max' => Options::v('comments_perpage'),
     'parent' => 0,
);
if (Comments::isEnable()) {
    echo '
     <div class="col-sm-12">
        <h3>Comments</h3>
         <div class="row">'.Comments::form().'<div class="clearfix">&nbsp;</div><hr />'.Comments::showList($comment).'</div>
      </div>
      ';
}
```

**Comment by AlexL777** [comment]
Thanks for that! 

Everything works again. Excellent!
