### ISSUE TITLE
User admin incorrect

### ISSUE THREAD

**Issue by raisiqueira** [semplon/GeniXCMS#9]
Hello, the admin user is with the wrong password, how do we reset without forgotpassword.php?

**Comment by semplon** [comment]
Hi, for that you can register a new user. access register.php at the browser. after the registration is done. go to the phpmyadmin and set the group of the new user with 0
now login with a new user. it's had a admin privilege. change the password of the admin. and now you can login with the previous admin.

**Comment by raisiqueira** [comment]
Return this error:
![screenshot_3](https://cloud.githubusercontent.com/assets/2914170/6643327/6880560e-c9a3-11e4-975b-aeba2dcb34e3.png)

**Comment by semplon** [comment]
thanks for the report. please take a look at your database options table. is there a value with name tokens ? if not insert a value with name tokens and value is empty.

I'll commit an update regarding the register.php files.

**Comment by semplon** [comment]
I'll try to make the forgotpassword file tonight. I just finished the Modules and Themes Installer. So we can create a custom themes and modules.

**Comment by raisiqueira** [comment]
Great, I will test the fixes that you did and come back to report if any error acontercer. I will wait the modules for creating themes ...: D

**Comment by semplon** [comment]
Hi, it's already done. Please try install the master branch. see the demo site for the showcase how themes and modules work.

I know why you can't login after install. it's the installer which had a bug and I've already improve it.
