### ISSUE TITLE
Treeview menu for Posts and Settings not working

### ISSUE THREAD

**Issue by prbt2016** [semplon/GeniXCMS#91]
Hello,

I manually installed GenixCMS 1.1.6 on PHP 7.2.7, Apache 2.2, MYSQL 5.5, Centos 6.4 . However post successful installation I found that the treeview menu for Posts and Settings are not working properly. Clicking on the pull right container ,shows no sub-categories under 'Posts' and 'Settings' categories, it's breaking.

Also only png images are loaded properly. Uploading other types of images and opening them shows 404 error.

Could you please fix this issue as soon as possible.?

**Comment by semplon** [comment]
Hello @prbt2016 i will check it soon. It seems i mistakenly remove the dashboard js file. 

You can download the master branch zip file. It is the full code. 

I will check again about the image. Not every images loaded properly when creating thumbnail. It's for security purpose.

**Comment by prbt2016** [comment]
Thanks :)

**Comment by semplon** [comment]
@prbt2016  can you use php 7.5.2 above ? some code require this version above.
